### PR TITLE
Publish slides

### PR DESCRIPTION
**Pull request by n4to4**
If you wouldn't mind, publishing the slides would be helpful when sharing to others.

### CODE REVIEW

**Comment by julien-truffaut** [comment]
Sure, what should I do to publish it after the merge?

**Comment by n4to4** [comment]
- Create an empty branch called `gh-pages`
- Go to `Settings` tab on GitHub, select `gh-pages branch` in `GitHub Pages` section.
- Run `sbt updateSite` to publish
- Access  https://julien-truffaut.github.io/jsonpath.pres/

**Comment by julien-truffaut** [comment]
Cheers, I am away from my computer. I will publish it tomorrow.
Thanks

**Comment by julien-truffaut** [comment]
@n4to4 It is published. Great idea!

**Comment by n4to4** [comment]
@julien-truffaut Cool. Putting the link on README would also be good, I think.

**Comment by julien-truffaut** [comment]
@n4to4 done, thanks

**Pull request merged**
